export const SEARCHFOCUS = 'header/search_focus'
export const SEARCHBLUR = 'header/search_blur'
export const CHANGELIST = 'header/change_list'
export const MOUSEENTER = 'header/mouse_enter'
export const MOUSELEAVE = 'header/mouse_leave'
export const CHANGEPAGE = 'header/change_page'